//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngSmart.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int ID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> unitID { get; set; }
        public Nullable<int> hightestPoint { get; set; }
        public Nullable<int> fistPoint { get; set; }
    }
}
