//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngSmart.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Pass { get; set; }
        public int Active { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Token { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<double> competence { get; set; }
    }
}
